In [18]:
import shutil
import os
file = 'ADNI'
new_path = 'Something'
def check_file(file_path):
    dst = 'Something'
    if file_path.endswith('nii'):
        shutil.move(file_path, dst)
    else:
        if (file_path.endswith('.DS_Store') == False):
            sub_folders = os.listdir(file_path)
            for sub_folder in sub_folders:
                new_path = file_path + '/' + sub_folder
                check_file(new_path)

In [19]:
check_file(file)

In [1]:
test_name = 'ab_cd_ef'
hold = test_name.split('_')
new_name = hold[-1]
new_name

'ef'

In [2]:
def rename_image(folder):
    if (folder.endswith('.DS_Store') == False):
            images = os.listdir(folder)
            for image in images:
                name = image
                name_list = name.split('_')
                new_path = folder + '/' + name_list[-1]
                old_path = folder + '/' + image
                os.rename(old_path, new_path)

In [5]:
import shutil
import os
rename_image('Something')

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('ADNI1_Complete_1Yr_3T_8_06_2021.csv')

In [3]:
df.head()

,Image Data ID,Subject,Group,Sex,Age,Visit,Modality,Description,Type,Acq Date,Format,Downloaded
0,I99265,136_S_1227,MCI,F,66,4,MRI,MPR; ; N3; Scaled,Processed,3/06/2008,NiFTI,8/05/2021
1,I79080,136_S_1227,MCI,F,65,3,MRI,MPR; ; N3; Scaled,Processed,9/11/2007,NiFTI,8/05/2021
2,I66824,136_S_1227,MCI,F,65,2,MRI,MPR; ; N3; Scaled,Processed,2/21/2007,NiFTI,8/05/2021
3,I82705,136_S_0579,MCI,F,66,3,MRI,MPR; ; N3; Scaled,Processed,1/08/2007,NiFTI,8/05/2021
4,I40404,136_S_0579,MCI,F,66,2,MRI,MPR-R; ; N3; Scaled,Processed,7/10/2006,NiFTI,8/05/2021

In [4]:
subjects = df['Subject'].tolist()

In [5]:
subjects

['136_S_1227',
 '136_S_1227',
 '136_S_1227',
 '136_S_0579',
 '136_S_0579',
 '136_S_0579',
 '136_S_0579',
 '136_S_0429',
 '136_S_0429',
 '136_S_0429',
 '136_S_0429',
 '136_S_0426',
 '136_S_0426',
 '136_S_0426',
 '136_S_0426',
 '136_S_0300',
 '136_S_0300',
 '136_S_0300',
 '136_S_0300',
 '136_S_0196',
 '136_S_0196',
 '136_S_0196',
 '136_S_0196',
 '136_S_0195',
 '136_S_0195',
 '136_S_0195',
 '136_S_0195',
 '136_S_0195',
 '136_S_0194',
 '136_S_0194',
 '136_S_0194',
 '136_S_0194',
 '136_S_0184',
 '136_S_0184',
 '136_S_0184',
 '136_S_0184',
 '136_S_0184',
 '136_S_0086',
 '136_S_0086',
 '136_S_0086',
 '136_S_0086',
 '130_S_1337',
 '130_S_1337',
 '130_S_1337',
 '130_S_0969',
 '130_S_0969',
 '130_S_0969',
 '130_S_0956',
 '130_S_0956',
 '130_S_0956',
 '130_S_0886',
 '130_S_0886',
 '130_S_0886',
 '130_S_0505',
 '130_S_0505',
 '130_S_0505',
 '130_S_0449',
 '130_S_0449',
 '130_S_0449',
 '130_S_0423',
 '130_S_0423',
 '130_S_0423',
 '128_S_1148',
 '128_S_1148',
 '128_S_1148',
 '128_S_1088',
 '128_S_1088',
 '128_S_1088',
 '127_S_0844',
 '127_S_0844',
 '127_S_0844',
 '127_S_0622',
 '127_S_0622',
 '127_S_0622',
 '127_S_0393',
 '127_S_0393',
 '127_S_0393',
 '127_S_0260',
 '127_S_0260',
 '127_S_0260',
 '126_S_0606',
 '126_S_0606',
 '126_S_0606',
 '116_S_1249',
 '116_S_1249',
 '116_S_1249',
 '116_S_1232',
 '116_S_1232',
 '116_S_1232',
 '116_S_0752',
 '116_S_0752',
 '116_S_0752',
 '116_S_0649',
 '116_S_0649',
 '116_S_0649',
 '116_S_0487',
 '116_S_0487',
 '116_S_0487',
 '116_S_0392',
 '116_S_0392',
 '116_S_0392',
 '116_S_0382',
 '116_S_0382',
 '116_S_0382',
 '100_S_1286',
 '100_S_1286',
 '100_S_1286',
 '100_S_0190',
 '100_S_0190',
 '100_S_0190',
 '100_S_0015',
 '100_S_0015',
 '100_S_0015',
 '094_S_1293',
 '094_S_1293',
 '094_S_1293',
 '094_S_1267',
 '094_S_1267',
 '094_S_1267',
 '094_S_1241',
 '094_S_1241',
 '094_S_1241',
 '082_S_1256',
 '082_S_1256',
 '082_S_1256',
 '082_S_0928',
 '082_S_0928',
 '082_S_0928',
 '067_S_1253',
 '067_S_1253',
 '067_S_1253',
 '067_S_0607',
 '067_S_0607',
 '067_S_0607',
 '067_S_0607',
 '067_S_0607',
 '067_S_0290',
 '067_S_0290',
 '067_S_0290',
 '067_S_0290',
 '053_S_0507',
 '053_S_0507',
 '053_S_0507',
 '053_S_0507',
 '053_S_0507',
 '053_S_0507',
 '052_S_1251',
 '052_S_1251',
 '052_S_1251',
 '052_S_1250',
 '052_S_1250',
 '052_S_1250',
 '051_S_1331',
 '051_S_1331',
 '051_S_1331',
 '051_S_1131',
 '051_S_1131',
 '051_S_1131',
 '051_S_1123',
 '051_S_1123',
 '051_S_1123',
 '051_S_1072',
 '051_S_1072',
 '051_S_1072',
 '037_S_1225',
 '037_S_1225',
 '037_S_1225',
 '037_S_0501',
 '037_S_0501',
 '037_S_0501',
 '037_S_0303',
 '037_S_0303',
 '037_S_0303',
 '032_S_1169',
 '032_S_1169',
 '032_S_1169',
 '032_S_1101',
 '032_S_1101',
 '032_S_1101',
 '032_S_0677',
 '032_S_0677',
 '032_S_0677',
 '031_S_1209',
 '031_S_1209',
 '031_S_1209',
 '031_S_1066',
 '031_S_1066',
 '031_S_1066',
 '031_S_0830',
 '031_S_0830',
 '027_S_1387',
 '027_S_1387',
 '027_S_1387',
 '027_S_1385',
 '027_S_1385',
 '027_S_1385',
 '027_S_1277',
 '027_S_1277',
 '027_S_1277',
 '027_S_1082',
 '027_S_1082',
 '027_S_1082',
 '027_S_1081',
 '027_S_1081',
 '027_S_1081',
 '027_S_0835',
 '027_S_0835',
 '027_S_0835',
 '027_S_0417',
 '027_S_0417',
 '027_S_0417',
 '027_S_0404',
 '027_S_0404',
 '027_S_0404',
 '027_S_0403',
 '027_S_0403',
 '027_S_0403',
 '027_S_0307',
 '027_S_0307',
 '027_S_0307',
 '023_S_1262',
 '023_S_1262',
 '023_S_1262',
 '023_S_1262',
 '023_S_1247',
 '023_S_1247',
 '023_S_1247',
 '023_S_1247',
 '023_S_1190',
 '023_S_1190',
 '023_S_1190',
 '023_S_1190',
 '023_S_1126',
 '023_S_1126',
 '023_S_1126',
 '023_S_1126',
 '023_S_1126',
 '023_S_1046',
 '023_S_1046',
 '023_S_1046',
 '023_S_1046',
 '023_S_1046',
 '023_S_0963',
 '023_S_0963',
 '023_S_0963',
 '023_S_0963',
 '023_S_0963',
 '023_S_0926',
 '023_S_0926',
 '023_S_0926',
 '023_S_0926',
 '023_S_0916',
 '023_S_0916',
 '023_S_0916',
 '023_S_0916',
 '023_S_0916',
 '023_S_0855',
 '023_S_0855',
 '023_S_0855',
 '023_S_0855',
 '023_S_0855',
 '023_S_0625',
 '023_S_0625',
 '023_S_0625',
 '023_S_0625',
 '023_S_0625',
 '023_S_0604',
 '023_S_0604',
 '023_S_0604',
 '023_S_0604',
 '023_S_0604',
 '023_S_0604',
 '023_S_0388',
 '023_S_0388',
 '023_S_0388',
 '023_S_0388',
 '023_S_0388',
 '023_S_0388',
 '023_S_0376',
 '023_S_0376',
 '023_S_0376',
 '023_S_0376',
 '023_S_0376',
 '023_S_0376',
 '023_S_0331',
 '023_S_0331',
 '023_S_0331',
 '023_S_0331',
 '023_S_0331',
 '023_S_0331',
 '023_S_0139',
 '023_S_0139',
 '023_S_0139',
 '023_S_0139',
 '023_S_0139',
 '023_S_0078',
 '023_S_0078',
 '023_S_0078',
 '023_S_0078',
 '023_S_0078',
 '023_S_0078',
 '023_S_0061',
 '023_S_0061',
 '023_S_0061',
 '023_S_0061',
 '023_S_0061',
 '023_S_0061',
 '023_S_0058',
 '023_S_0058',
 '023_S_0058',
 '023_S_0058',
 '023_S_0058',
 '023_S_0031',
 '023_S_0031',
 '023_S_0031',
 '023_S_0031',
 '023_S_0031',
 '023_S_0031',
 '023_S_0030',
 '023_S_0030',
 '023_S_0030',
 '023_S_0030',
 '023_S_0030',
 '021_S_0332',
 '021_S_0332',
 '021_S_0332',
 '018_S_0633',
 '018_S_0633',
 '018_S_0633',
 '018_S_0450',
 '018_S_0450',
 '018_S_0450',
 '018_S_0425',
 '018_S_0425',
 '018_S_0425',
 '018_S_0406',
 '018_S_0406',
 '018_S_0406',
 '018_S_0369',
 '018_S_0369',
 '018_S_0369',
 '018_S_0369',
 '018_S_0335',
 '018_S_0335',
 '018_S_0335',
 '016_S_1326',
 '016_S_1326',
 '016_S_1326',
 '016_S_1121',
 '016_S_1121',
 '016_S_1121',
 '016_S_1117',
 '016_S_1117',
 '016_S_1117',
 '016_S_0769',
 '016_S_0769',
 '016_S_0769',
 '012_S_1321',
 '012_S_1321',
 '012_S_1321',
 '012_S_1292',
 '012_S_1292',
 '012_S_1292',
 '012_S_1009',
 '012_S_1009',
 '012_S_1009',
 '012_S_0689',
 '012_S_0689',
 '012_S_0689',
 '007_S_1222',
 '007_S_1222',
 '007_S_1222',
 '007_S_1206',
 '007_S_1206',
 '007_S_1206',
 '005_S_0814',
 '005_S_0814',
 '005_S_0814',
 '005_S_0602',
 '005_S_0602',
 '005_S_0602',
 '005_S_0572',
 '005_S_0572',
 '005_S_0572',
 '005_S_0553',
 '005_S_0553',
 '005_S_0553',
 '005_S_0448',
 '005_S_0448',
 '005_S_0448',
 '005_S_0324',
 '005_S_0324',
 '005_S_0324',
 '002_S_1280',
 '002_S_1280',
 '002_S_1280',
 '002_S_1268',
 '002_S_1268',
 '002_S_1268',
 '002_S_1261',
 '002_S_1261',
 '002_S_1261',
 '002_S_1070',
 '002_S_1070',
 '002_S_1070',
 '002_S_1018',
 '002_S_1018',
 '002_S_1018',
 '002_S_0954',
 '002_S_0954',
 '002_S_0954',
 '002_S_0954',
 '002_S_0559',
 '002_S_0559',
 '002_S_0559',
 '002_S_0559',
 '002_S_0413',
 '002_S_0413',
 '002_S_0413',
 '002_S_0413']

In [6]:
subject_unique = set(subjects)

In [7]:
subject_unique

{'002_S_0413',
 '002_S_0559',
 '002_S_0954',
 '002_S_1018',
 '002_S_1070',
 '002_S_1261',
 '002_S_1268',
 '002_S_1280',
 '005_S_0324',
 '005_S_0448',
 '005_S_0553',
 '005_S_0572',
 '005_S_0602',
 '005_S_0814',
 '007_S_1206',
 '007_S_1222',
 '012_S_0689',
 '012_S_1009',
 '012_S_1292',
 '012_S_1321',
 '016_S_0769',
 '016_S_1117',
 '016_S_1121',
 '016_S_1326',
 '018_S_0335',
 '018_S_0369',
 '018_S_0406',
 '018_S_0425',
 '018_S_0450',
 '018_S_0633',
 '021_S_0332',
 '023_S_0030',
 '023_S_0031',
 '023_S_0058',
 '023_S_0061',
 '023_S_0078',
 '023_S_0139',
 '023_S_0331',
 '023_S_0376',
 '023_S_0388',
 '023_S_0604',
 '023_S_0625',
 '023_S_0855',
 '023_S_0916',
 '023_S_0926',
 '023_S_0963',
 '023_S_1046',
 '023_S_1126',
 '023_S_1190',
 '023_S_1247',
 '023_S_1262',
 '027_S_0307',
 '027_S_0403',
 '027_S_0404',
 '027_S_0417',
 '027_S_0835',
 '027_S_1081',
 '027_S_1082',
 '027_S_1277',
 '027_S_1385',
 '027_S_1387',
 '031_S_0830',
 '031_S_1066',
 '031_S_1209',
 '032_S_0677',
 '032_S_1101',
 '032_S_1169',
 '037_S_0303',
 '037_S_0501',
 '037_S_1225',
 '051_S_1072',
 '051_S_1123',
 '051_S_1131',
 '051_S_1331',
 '052_S_1250',
 '052_S_1251',
 '053_S_0507',
 '067_S_0290',
 '067_S_0607',
 '067_S_1253',
 '082_S_0928',
 '082_S_1256',
 '094_S_1241',
 '094_S_1267',
 '094_S_1293',
 '100_S_0015',
 '100_S_0190',
 '100_S_1286',
 '116_S_0382',
 '116_S_0392',
 '116_S_0487',
 '116_S_0649',
 '116_S_0752',
 '116_S_1232',
 '116_S_1249',
 '126_S_0606',
 '127_S_0260',
 '127_S_0393',
 '127_S_0622',
 '127_S_0844',
 '128_S_1088',
 '128_S_1148',
 '130_S_0423',
 '130_S_0449',
 '130_S_0505',
 '130_S_0886',
 '130_S_0956',
 '130_S_0969',
 '130_S_1337',
 '136_S_0086',
 '136_S_0184',
 '136_S_0194',
 '136_S_0195',
 '136_S_0196',
 '136_S_0300',
 '136_S_0426',
 '136_S_0429',
 '136_S_0579',
 '136_S_1227'}

In [8]:
len(subject_unique)

119

In [9]:
test = df.loc[(df['Subject'] == '002_S_0413')&(df['Visit'] == 2)]

In [10]:
hold = test.iloc[0]

In [11]:
image_id = hold['Image Data ID']

In [12]:
image_id

'I118675'

In [13]:
df_2 = pd.DataFrame()

In [14]:
df_2['subject'] = list(subject_unique)

In [15]:
df_2

        subject
0    136_S_0300
1    067_S_0290
2    012_S_1292
3    023_S_0139
4    051_S_1131
..          ...
114  027_S_1387
115  027_S_0307
116  023_S_0331
117  116_S_0382
118  136_S_0196

[119 rows x 1 columns]

In [16]:
def get_visit2(subject):
    hold1 = df.loc[(df['Subject'] == subject)&(df['Visit'] == 2)]
    hold2 = hold1.iloc[0]
    image_id = hold2['Image Data ID']
    return image_id

In [17]:
df_2['visit_2'] = df_2['subject'].apply(get_visit2)
df_2.head()

      subject  visit_2
0  136_S_0300  I119729
1  067_S_0290  I119201
2  012_S_1292   I74691
3  023_S_0139   I31313
4  051_S_1131   I64929

In [18]:
import numpy as np
def get_visit3(subject):
    try:
        hold1 = df.loc[(df['Subject'] == subject)&(df['Visit'] == 3)]
        hold2 = hold1.iloc[0]
        image_id = hold2['Image Data ID']
        return image_id
    except:
        return np.nan
def get_visit4(subject):
    try:
        hold1 = df.loc[(df['Subject'] == subject)&(df['Visit'] == 4)]
        hold2 = hold1.iloc[0]
        image_id = hold2['Image Data ID']
        return image_id
    except:
        return np.nan

In [19]:
df_2['visit_3'] = df_2['subject'].apply(get_visit3)

df_2['visit_4'] = df_2['subject'].apply(get_visit4)

df_2.head()

      subject  visit_2  visit_3  visit_4
0  136_S_0300  I119729   I66754   I66768
1  067_S_0290  I119201   I86402   I72427
2  012_S_1292   I74691   I78796  I103301
3  023_S_0139   I31313  I119007   I52049
4  051_S_1131   I64929   I73127   I91833

In [20]:
df_2.loc[df_2['visit_4']== np.nan]

Empty DataFrame
Columns: [subject, visit_2, visit_3, visit_4]
Index: []

In [33]:
def get_group(subject):
    try:
        hold1 = df.loc[df['Subject'] == subject]
        hold2 = hold1.iloc[0]
        image_id = hold2['Group']
        return image_id
    except:
        return np.nan

In [34]:
df_2['group'] = df_2['subject'].apply(get_group)
df_2.head()

,subject,visit_2,visit_3,visit_4,group,image_3,image_4,image_2
0,136_S_0300,I119729,I66754,I66768,AD,"[-1.2959750263236734e-22, 1.089098306229994e-1...","[0.0, 1.2037062152420224e-35, 1.73333694994851...","[1.1107161545511846e-26, 3.2460869448246603e-2..."
1,067_S_0290,I119201,I86402,I72427,MCI,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0...","[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2,012_S_1292,I74691,I78796,I103301,MCI,"[0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0...","[0.0, 2.117582368135751e-22, 1.592322679164578...","[0.0, -0.0, -0.0, -0.0, -8.407790785948902e-45..."
3,023_S_0139,I31313,I119007,I52049,AD,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,051_S_1131,I64929,I73127,I91833,MCI,"[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0....","[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0...."

In [23]:
!pip install SimpleITK
import SimpleITK as sitk
#170, 256, 256
#thank you other worker
def resample_img(itk_image, out_spacing=[2.0, 2.0, 2.0]):
    ''' This function resamples images to 2-mm isotropic voxels.
      
        Parameters:
            itk_image -- Image in simpleitk format, not a numpy array
            out_spacing -- Space representation of each voxel
            
        Returns: 
            Resulting image in simpleitk format, not a numpy array
    '''
    
    # Resample images to 2mm spacing with SimpleITK
    original_spacing = itk_image.GetSpacing()
    original_size = itk_image.GetSize()

    out_size = [
        int(np.round(original_size[0] * (original_spacing[0] / out_spacing[0]))),
        int(np.round(original_size[1] * (original_spacing[1] / out_spacing[1]))),
        int(np.round(original_size[2] * (original_spacing[2] / out_spacing[2])))]

    resample = sitk.ResampleImageFilter()
    resample.SetOutputSpacing(out_spacing)
    resample.SetSize(out_size)
    resample.SetOutputDirection(itk_image.GetDirection())
    resample.SetOutputOrigin(itk_image.GetOrigin())
    resample.SetTransform(sitk.Transform())
    resample.SetDefaultPixelValue(itk_image.GetPixelIDValue())

    resample.SetInterpolator(sitk.sitkBSpline)

    return resample.Execute(itk_image)

Collecting SimpleITK
  Using cached SimpleITK-2.1.0-cp38-cp38-macosx_10_9_x86_64.whl (44.3 MB)
Installing collected packages: SimpleITK
Successfully installed SimpleITK-2.1.0

In [24]:
def get_image(subject):
    path = 'Something/' + subject
    image = sitk.ReadImage(path)
    image = resample_img(image)
    return image

In [25]:
df_2.dropna(inplace = True)

In [46]:
image_test = get_image('I119729')

In [51]:
img = sitk.GetArrayFromImage(image_test)
img.shape

(102, 128, 128)

In [27]:
df_2['image_2'] = df_2['visit_2'].apply(get_image)
df_2['image_3'] = df_2['visit_3'].apply(get_image)
df_2['image_4'] = df_2['visit_4'].apply(get_image)

In [28]:
df_2.head()

,subject,visit_2,visit_3,visit_4,group,image_3,image_4,image_2
0,136_S_0300,I119729,I66754,I66768,CN,"[-1.2959750263236734e-22, 1.089098306229994e-1...","[0.0, 1.2037062152420224e-35, 1.73333694994851...","[1.1107161545511846e-26, 3.2460869448246603e-2..."
1,067_S_0290,I119201,I86402,I72427,CN,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0...","[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2,012_S_1292,I74691,I78796,I103301,CN,"[0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0...","[0.0, 2.117582368135751e-22, 1.592322679164578...","[0.0, -0.0, -0.0, -0.0, -8.407790785948902e-45..."
3,023_S_0139,I31313,I119007,I52049,CN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,051_S_1131,I64929,I73127,I91833,CN,"[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0....","[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0...."

In [35]:
x = df_2[['image_2','image_3','image_4']]
y = df_2['group']

In [36]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 16)

In [37]:
import tensorflow as tf
import tensorflow.keras

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=30,activation = 'relu',input_shape=(102,128,128,3)))
model.add(Dense(units=30,activation = 'relu'))
model.add(Dense(units=30,activation = 'relu'))
model.add(Dense(units=30,activation = 'relu'))
model.add(Dense(units=3, activation = 'softmax'))

In [59]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['Recall'])
history = model.fit(x_train, y_train, epochs=1,
                    validation_data=(x_test, y_test))

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type Image).